# -*- coding: utf-8 -*-
"""wine_quality.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q-lCYATyEGpFiQxtDDhYI9XyIG2BB0d7
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('winequality-red.csv')
df

df.isnull().sum()

df.describe()

df.info()

# fixed acidity, volatile acidity,citric acid,
# residual sugar, chlorides, free sulfur dioxide, total sulfur dioxide, density,
# pH, pulphates, alcohol
df.head(24)

# df.groupby('quality').mean()

plt.bar(df['quality'], df['volatile acidity'], width=0.5)
plt.xlabel("Quality")
plt.ylabel("Volatile Acidity")
plt.title("Bar Plot of Quality vs Volatile Acidity")
plt.show()

# Corrected column name
counts, bin_edges, _ = plt.hist(df['volatile acidity'], bins=5, color='green', alpha=0.5)  # Get counts and bin edges
plt.clf()  # Clear the current histogram plot

# Create bar plot with gaps
bar_width = (bin_edges[1] - bin_edges[0]) * 0.8  # Adjust bar width to add gaps
bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2  # Compute the centers of the bins

plt.bar(bin_centers, counts, width=bar_width, color='green', edgecolor='black')  # Bar plot with gaps
plt.xlabel("Volatile Acidity")
plt.ylabel("Frequency")
plt.title("Histogram of Volatile Acidity (with Gaps)")
plt.show()

# Box plot
plt.boxplot(df['volatile acidity'], patch_artist=True, boxprops=dict(facecolor='lightgreen'))
plt.xlabel("Volatile Acidity")
plt.title("Box Plot of Volatile Acidity")
plt.show()

"""# Feature selection"""

df.sample(5)

df['quality'].unique()

# # if wine quality is 7 or above then will consider as good quality wine
# df['good_quality'] = df['quality'] >= 7

# # Display the DataFrame
# print(df.head())

# # Count good quality wines
# print("Good quality wines count:", df['good_quality'].sum())

good_quality_wines = df[df['quality'] >= 7]

# Display good quality wines
print(good_quality_wines)

# Count the number of good quality wines
print("Number of good quality wines:", len(good_quality_wines))

# if wine quality is 7 or above then will consider as good quality wine

df['gooodquality'] = [1  if x>= 7 else 0 for x in df['quality']]
df.sample(5)

# separate dependent and independent variables
x = df.drop(['quality', 'gooodquality'], axis=1)
y = df['gooodquality']

# see total number of good vs bad wines samples
df['gooodquality'].value_counts()

print(x)

y

"""# Feature Importance"""

# see how huch each feature is contributing

from sklearn.ensemble import ExtraTreesClassifier
model = ExtraTreesClassifier()
model.fit(x,y)
score = model.feature_importances_
score

"""# Splitting Dataset"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=7)

# result
model_res = pd.DataFrame(columns=['Model','Score'])

"""# logistics regression"""

from sklearn.linear_model import LogisticRegression
mdoel = LogisticRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

from sklearn.metrics import accuracy_score,confusion_matrix
model_res.loc[len(model_res)] = ['LogisticRegression', accuracy_score(y_test,y_pred)]
model_res

from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=3)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

from sklearn.metrics import accuracy_score,confusion_matrix
model_res.loc[len(model_res)] = ['KNeighborsCLassifier', accuracy_score(y_test,y_pred)]
model_res

"""# SVC"""

from sklearn.svm import SVC
model = SVC()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

from sklearn.metrics import accuracy_score
print("Accuracy Score:",accuracy_score(y_test,y_pred))
model_res.loc[len(model_res)] = ['SVC', accuracy_score(y_test,y_pred)]
model_res

"""# Using Decision Tree"""

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(criterion='entropy',random_state=7)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

from sklearn.metrics import accuracy_score
print("Accuracy Score:",accuracy_score(y_test,y_pred))
model_res.loc[len(model_res)] = ['DecisionTreeClassifier', accuracy_score(y_test,y_pred)]
model_res

"""# Using GaussionNB"""

from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

from sklearn.metrics import accuracy_score
print("Accuracy Score:",accuracy_score(y_test,y_pred))
model_res.loc[len(model_res)] = ['GaussianNB', accuracy_score(y_test,y_pred)]
model_res

"""
# Using Random Forest

"""

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(random_state=1)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

from sklearn.metrics import accuracy_score
print("Accuracy Score:",accuracy_score(y_test,y_pred))
model_res.loc[len(model_res)] = ['RandomForestClassifier', accuracy_score(y_test,y_pred)]
model_res

import xgboost as xgb
model = xgb.XGBClassifier(random_state=1)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

from sklearn.metrics import accuracy_score
print("Accuracy Score:",accuracy_score(y_test,y_pred))
model_res.loc[len(model_res)] = ['XGBClassifier', accuracy_score(y_test,y_pred)]
model_res

model_res = model_res.sort_values(by='Score', ascending=False)
model_res